name: 'Test Unit'
description: 'Running unit tests'
inputs:
  github_token:
    description: "Github Token"
    required: true
  codecov_token:
    description: "CodeCov Token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@v1

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast --target ${{ matrix.config.target }}
      env:
        RUST_TEST_THREADS: '2'
        RUST_LOG: ERROR
        RUST_BACKTRACE: full
        RUSTFLAGS: '-Zprofile'

    - name: Install grcov
      if: '{{ matrix.config.target }} == "x86_64-unknown-linux-gnu"'
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: grcov

    - name: Run code coverage
      if: '{{ matrix.config.target }} == "x86_64-unknown-linux-gnu"'
      uses: actions-rs/grcov@v0.1.5
      id: coverage

    - name: Upload to codecov.io
      if: '{{ matrix.config.target }} == "x86_64-unknown-linux-gnu"'
      uses: codecov/codecov-action@v1
      with:
        token: ${{ inputs.codecov_token }}
        file: ${{ steps.coverage.outputs.report }}
